language: node_js
node_js:
  - 'stable'
script:
  - npm run build
deploy:
  provider: s3
  skip_cleanup: true
  local_dir: build
  region: ${AWS_BUCKET_REGION}
  bucket: ${AWS_BUCKET_NAME}
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(staging|main)$
branches:
  only:
    - main
    # - staging
